import { expect, test } from '@playwright/test'
const articleURL = '/posts/' + encodeURIComponent('привет-старый-веб')

test('one real audio element continues across routes and shares inline controls/volume', async ({ page }, testInfo) => {
  await page.addInitScript(() => localStorage.setItem('stereodamage_audio_volume_v1', '0.35'))
  await page.goto(articleURL)
  const audio = page.locator('#persistent-audio')
  await expect(audio).toHaveCount(1)
  await expect(audio).not.toHaveAttribute('src')
  await page.getByRole('button', { name: 'Слушать: Тестовый трек', exact: true }).click()
  await expect.poll(() => audio.evaluate(element => (element as HTMLAudioElement).paused)).toBe(false)
  await expect.poll(() => audio.evaluate(element => (element as HTMLAudioElement).currentTime)).toBeGreaterThan(0)
  await expect(audio).toHaveJSProperty('volume', 0.35)
  await page.screenshot({ path: testInfo.outputPath('audio-player.png') })
  await audio.evaluate(element => { (element as HTMLAudioElement).currentTime = 5; element.setAttribute('data-original-player', 'yes') })
  await page.getByRole('button', { name: 'Назад к ленте', exact: true }).click()
  await expect(page.locator('.feed-list')).toBeVisible()
  await expect(audio).toHaveAttribute('data-original-player', 'yes')
  await expect.poll(() => audio.evaluate(element => (element as HTMLAudioElement).currentTime)).toBeGreaterThan(5)
  await expect(page.getByRole('button', { name: 'Пауза: attachment-2', exact: true })).toBeVisible()
  await page.locator('#post-title-2 a').click()
  await expect(page.locator('.post-body')).toBeVisible()
  await expect(audio).toHaveJSProperty('paused', false)
  await page.getByRole('link', { name: 'StereoDamage — Главная', exact: true }).click()
  await page.locator('#post-title-1 a').click()
  await page.getByRole('button', { name: 'Пауза: Тестовый трек', exact: true }).click()
  await expect(audio).toHaveJSProperty('paused', true)
  await page.getByRole('button', { name: 'Слушать: Тестовый трек', exact: true }).click()
  await expect(audio).toHaveJSProperty('paused', false)
  const volume = page.getByRole('slider', { name: 'Громкость' })
  await volume.focus()
  await volume.press('Home')
  for (let step = 0; step < 20; step++) await volume.press('ArrowRight')
  await expect(audio).toHaveJSProperty('volume', 0.2)
  expect(await page.evaluate(() => localStorage.getItem('stereodamage_audio_volume_v1'))).toBe('0.2')
  await page.getByRole('button', { name: 'Закрыть плеер', exact: true }).click()
  await expect(audio).not.toHaveAttribute('src')
  await expect(audio).toHaveJSProperty('paused', true)
  await expect(page.locator('.mini-player')).not.toBeVisible()
  await expect(page.locator('audio')).toHaveCount(1)
})

test('audio failures are recoverable and blocked storage does not prevent playback', async ({ page }) => {
  await page.addInitScript(() => { Object.defineProperty(window, 'localStorage', { get() { throw new Error('Blocked') } }) })
  await page.route('**/uploads/fixture.wav', route => route.fulfill({ status: 404, body: '' }))
  await page.goto(articleURL)
  await page.getByRole('button', { name: 'Слушать: Тестовый трек', exact: true }).click()
  await expect(page.locator('.mini-player [role="status"]')).toBeVisible()
  await page.unroute('**/uploads/fixture.wav')
  await page.getByRole('button', { name: 'Слушать: Тестовый трек', exact: true }).click()
  await expect(page.locator('#persistent-audio')).toHaveJSProperty('paused', false)
})
