import { expect, test } from '@playwright/test'

test('real anonymous, named, reply, pending and comment-like flows', async ({ page }, testInfo) => {
  const post = testInfo.project.name === 'mobile' ? 21 : 20
  await page.goto(`/posts/fixture-${post}`)
  const form = page.locator('.comment-form')
  const text = page.getByRole('textbox', { name: 'Комментарий', exact: true })
  const name = page.getByRole('textbox', { name: 'Имя (необязательно)', exact: true })
  const submit = page.getByRole('button', { name: 'Отправить комментарий', exact: true })
  const anonymous = `Мне нравится читать длинные истории на личных сайтах. ${testInfo.project.name}`
  await text.fill(anonymous)
  await expect(form.locator('input[name^="hp_"]')).toHaveCount(1)
  await submit.click()
  await expect(form.getByRole('status')).toHaveText('Комментарий опубликован.')
  const first = page.locator('.comment-item').filter({ hasText: anonymous })
  await expect(first.locator('strong')).toHaveText('Анон')
  await first.getByRole('button', { name: 'Лайк комментарию: Анон', exact: true }).click()
  await expect(first.getByRole('button', { name: 'Лайк комментарию: Анон', exact: true })).toContainText('1')
  await page.waitForTimeout(1100)
  await name.fill('Reader')
  await text.fill('Спасибо за интересный рассказ о самостоятельных сайтах и их истории.')
  await submit.click()
  await expect(page.locator('.comment-item strong').last()).toHaveText('Reader')
  await page.waitForTimeout(1100)
  await first.getByRole('button', { name: 'Ответить', exact: true }).click()
  await expect(page.locator('.reply-context')).toContainText('Ответ для Анон')
  await expect(page.locator('form')).toHaveCount(1)
  await text.fill('<b>Это простой текст ответа, а не HTML.</b>')
  await submit.click()
  await expect(page.locator('.comment-parent')).toHaveCount(1)
  await expect(page.locator('.comment-text b')).toHaveCount(0)
  await expect(page.getByText('<b>Это простой текст ответа, а не HTML.</b>', { exact: true })).toBeVisible()
  await page.waitForTimeout(1100)
  await name.fill('https://name.example')
  await text.fill('https://a.example https://b.example')
  await submit.click()
  await expect(form.getByRole('status')).toHaveText('Комментарий принят и появится после проверки.')
  await expect(page.locator('.comment-item')).toHaveCount(3)
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
})

test('rate errors preserve drafts and deeply nested comments keep usable width', async ({ page }) => {
  await page.route('**/api/v1/posts/22/comments', async (route) => {
    if (route.request().method() === 'POST') return route.fulfill({ status: 429, json: { error: { code: 'comment_rate_limited', message: 'Wait' } } })
    return route.fulfill({ json: Array.from({ length: 20 }, (_, i) => ({ id: i + 100, post_id: 22, parent_id: i ? i + 99 : null, name: null, content: `Reply ${i}`, likes: 0, created_at: '2026-01-01T00:00:00Z' })) })
  })
  await page.goto('/admin')
  await page.evaluate(() => { location.hash = '' })
  // Enter through Nuxt navigation so the comments read is intercepted in the browser.
  await page.getByRole('link', { name: 'StereoDamage — Главная', exact: true }).click()
  for (const count of [20, 30]) {
    await page.locator('.feed-pagination').scrollIntoViewIfNeeded()
    await expect(page.locator('.feed-post')).toHaveCount(count)
  }
  await page.locator('#post-title-22 a').click()
  await expect(page.locator('.comment-item')).toHaveCount(20)
  const width = await page.locator('.comment-item').last().evaluate(node => node.getBoundingClientRect().width)
  expect(width).toBeGreaterThan(250)
  const text = page.getByRole('textbox', { name: 'Комментарий', exact: true })
  await text.fill('Текст не должен пропасть при временной ошибке отправки.')
  await page.getByRole('button', { name: 'Отправить комментарий', exact: true }).click()
  await expect(page.locator('.comment-form [role="status"]')).toContainText('Слишком частые сообщения')
  await expect(text).toHaveValue('Текст не должен пропасть при временной ошибке отправки.')
})
