import { expect, test } from '@playwright/test'

test('editor loads only after admin login and supports ordinary paragraph entry', async ({ page }) => {
  const editorChunks: string[] = []
  page.on('response', async response => {
    if (response.url().endsWith('.js') && (await response.text().catch(() => '')).includes('ProseMirror')) editorChunks.push(response.url())
  })
  await page.goto('/', { waitUntil: 'networkidle' })
  expect(editorChunks).toEqual([])
  await page.goto('/admin', { waitUntil: 'networkidle' })
  expect(editorChunks).toEqual([])
  await page.locator('#admin-secret').fill('browser-test-secret')
  await page.getByRole('button', { name: 'Войти', exact: true }).click()
  const body = page.getByRole('textbox', { name: 'Текст поста' })
  await expect(body).toBeVisible()
  await body.fill('Первый абзац')
  await body.press('End')
  await body.press('Enter')
  await page.keyboard.type('Second paragraph')
  await expect(body.locator('p')).toHaveCount(2)
  await page.getByLabel('Заголовок', { exact: true }).fill('Черновик')
  await body.press('ControlOrMeta+a')
  await page.getByRole('button', { name: 'Жирный', exact: true }).click()
  await expect(body.locator('strong')).toHaveCount(2)
  await page.getByRole('button', { name: 'Отменить', exact: true }).click()
  await expect(body.locator('strong')).toHaveCount(0)
  await page.getByRole('button', { name: 'Повторить', exact: true }).click()
  await expect(body.locator('strong')).toHaveCount(2)
  await body.press('ArrowRight')
  await page.getByRole('button', { name: 'Заголовок раздела 2', exact: true }).click()
  await expect(body.locator('h2')).toBeVisible()
  await page.getByRole('button', { name: 'Абзац', exact: true }).click()
  await page.getByRole('button', { name: 'Цитата', exact: true }).click()
  await expect(body.locator('blockquote')).toBeVisible()
  await page.getByText('Настройки поста', { exact: true }).click()
  await page.getByLabel('Slug (необязательно)').fill('test-draft')
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
  expect(editorChunks.length).toBeGreaterThan(0)
})
