import { expect, test } from '@playwright/test'

test('editor loads only after admin login and supports ordinary paragraph entry', async ({ page }) => {
  const editorChunks: string[] = []
  page.on('response', async response => {
    if (response.url().endsWith('.js') && (await response.text().catch(() => '')).includes('ProseMirror')) editorChunks.push(response.url())
  })
  await page.goto('/', { waitUntil: 'networkidle' })
  expect(editorChunks).toEqual([])
  await page.goto('/admin', { waitUntil: 'networkidle' })
  expect(editorChunks).toEqual([])
  await page.locator('#admin-secret').fill('browser-test-secret')
  await page.getByRole('button', { name: 'Войти', exact: true }).click()
  const body = page.getByRole('textbox', { name: 'Текст поста' })
  await expect(body).toBeVisible()
  await body.fill('Первый абзац')
  await body.press('End')
  await body.press('Enter')
  await page.keyboard.type('Second paragraph')
  await expect(body.locator('p')).toHaveCount(2)
  await page.getByLabel('Заголовок', { exact: true }).fill('Черновик')
  await body.press('ControlOrMeta+a')
  await page.getByRole('button', { name: 'Жирный', exact: true }).click()
  await expect(body.locator('strong')).toHaveCount(2)
  await page.getByRole('button', { name: 'Отменить', exact: true }).click()
  await expect(body.locator('strong')).toHaveCount(0)
  await page.getByRole('button', { name: 'Повторить', exact: true }).click()
  await expect(body.locator('strong')).toHaveCount(2)
  await body.press('ArrowRight')
  await page.getByRole('button', { name: 'Заголовок раздела 2', exact: true }).click()
  await expect(body.locator('h2')).toBeVisible()
  await page.getByRole('button', { name: 'Абзац', exact: true }).click()
  await page.getByRole('button', { name: 'Цитата', exact: true }).click()
  await expect(body.locator('blockquote')).toBeVisible()
  await page.getByText('Настройки поста', { exact: true }).click()
  await page.getByLabel('Slug (необязательно)').fill('test-draft')
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
  expect(editorChunks.length).toBeGreaterThan(0)
  await body.click()
  await body.press('ControlOrMeta+End')
  const file = { name: 'notes.txt', mimeType: 'text/plain', buffer: Buffer.from('A small attachment') }
  await page.route('**/api/v1/admin/uploads', route => route.abort())
  await page.locator('input[type=file]').setInputFiles(file)
  await expect(page.getByRole('alert')).toBeVisible()
  await expect(body.locator('figure')).toHaveCount(0)
  await expect(page.getByText('Черновик сохранён на этом устройстве.', { exact: true })).toBeVisible()
  await page.reload()
  await expect(page.getByText('Восстановлен локальный черновик. Изменения ещё не опубликованы.')).toBeVisible()
  await expect(page.getByLabel('Заголовок', { exact: true })).toHaveValue('Черновик')
  await expect(body).toContainText('Первый абзац')
  await page.getByRole('button', { name: 'Предпросмотр', exact: true }).click()
  await expect(page.locator('article.post-article .post-body')).toContainText('Первый абзац')
  await expect(body).toBeHidden()
  await page.getByRole('button', { name: 'Вернуться к редактированию', exact: true }).click()
  await expect(body).toBeVisible()
  page.once('dialog', dialog => dialog.accept())
  await page.getByRole('button', { name: 'Сбросить черновик', exact: true }).click()
  await expect(page.getByLabel('Заголовок', { exact: true })).toHaveValue('')
  await expect(body).toHaveText('')
  await page.reload()
  await expect(body).toHaveText('')
  await page.unroute('**/api/v1/admin/uploads')
  const picker = page.waitForEvent('filechooser')
  await page.getByRole('button', { name: 'Добавить медиа / файл' }).click()
  await (await picker).setFiles(file)
  await expect(body.locator('figure')).toHaveText('notes.txt')
  await body.locator('figure').click()
  await page.getByLabel('Подпись', { exact: true }).fill('Caption')
  await page.getByLabel('Подпись', { exact: true }).press('Tab')
  await page.getByLabel('Спойлер', { exact: true }).check()
  await page.getByRole('button', { name: 'Убрать медиа', exact: true }).click()
  await expect(body.locator('figure')).toHaveCount(0)
})
