import { expect, test } from '@playwright/test'

for (const language of ['ru', 'en']) {
  test(`moderation uses real protected APIs and safe text (${language})`, async ({ page, context }, info) => {
    const ru = language === 'ru'
    const base = 20000 + ((info.project.name === 'desktop' ? 0 : 2) + (ru ? 0 : 1)) * 10
    await page.addInitScript(language => localStorage.setItem('stereoDamageLanguage', language), language)
    expect((await page.request.get('/api/v1/admin/moderation')).status()).toBe(401)
    await page.goto('/admin')
    await page.locator('#admin-secret').fill('browser-test-secret')
    await page.getByRole('button', { name: ru ? 'Войти' : 'Sign in', exact: true }).click()
    const area = page.locator('#admin-moderation')
    const comment = (id: number) => area.locator(`[data-comment-id="${id}"]`)
    await expect(comment(base)).toContainText('<img src=x onerror=alert(1)>')
    await expect(area.locator('img, script')).toHaveCount(0)
    await expect(page.locator('nav a[href="#admin-moderation"]')).toContainText(/\(\d+\)/)
    expect((await page.request.post(`/api/v1/admin/comments/${base}/approve`, { data: {} })).status()).toBe(403)
    await page.route(`**/api/v1/admin/comments/${base}/approve`, route => route.abort())
    await comment(base).getByRole('button', { name: ru ? 'Одобрить' : 'Approve', exact: true }).click()
    await expect(area.getByRole('alert')).toBeVisible()
    await expect(comment(base)).toBeVisible()
    await page.unroute(`**/api/v1/admin/comments/${base}/approve`)
    await comment(base).getByRole('button', { name: ru ? 'Одобрить' : 'Approve', exact: true }).click()
    await expect(comment(base)).toHaveCount(0)
    let visible = await (await page.request.get('/api/v1/posts/32/comments')).json()
    expect(visible.some((comment: { id: number }) => comment.id === base)).toBe(true)
    await comment(base + 1).getByRole('button', { name: ru ? 'Отклонить' : 'Reject', exact: true }).click()
    await expect(comment(base + 1)).toHaveCount(0)
    visible = await (await page.request.get('/api/v1/posts/32/comments')).json()
    expect(visible.some((comment: { id: number }) => comment.id === base + 1)).toBe(false)
    page.once('dialog', dialog => dialog.dismiss())
    await comment(base + 2).getByRole('button', { name: ru ? 'Удалить ветку' : 'Delete thread', exact: true }).click()
    await expect(comment(base + 2)).toBeVisible()
    page.once('dialog', dialog => dialog.accept())
    await comment(base + 2).getByRole('button', { name: ru ? 'Удалить ветку' : 'Delete thread', exact: true }).click()
    await expect(comment(base + 2)).toHaveCount(0)
    await expect(comment(base + 3)).toHaveCount(0)
    await area.locator('summary').click()
    const mute = area.locator(`[data-mute-id="${base}"]`)
    await expect(mute).toBeVisible()
    await expect(area).not.toContainText('private-suffix')
    await expect(area.locator(`[data-attempt-id="${base}"]`)).toContainText('<script>untrusted</script>')
    await mute.getByRole('button', { name: ru ? 'Снять блокировку' : 'Unmute', exact: true }).click()
    await expect(mute).toHaveCount(0)
    expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
    const session = await (await page.request.get('/api/v1/admin/session')).json()
    for (const id of [base, base + 1]) await page.request.delete(`/api/v1/admin/comments/${id}`, { headers: { 'X-CSRF-Token': session.csrf_token } })
    await page.route('**/api/v1/admin/moderation', route => route.abort())
    await area.getByRole('button', { name: ru ? 'Обновить список' : 'Refresh list', exact: true }).click()
    await expect(area.getByRole('alert')).toBeVisible()
    await page.unroute('**/api/v1/admin/moderation')
    await area.getByRole('button', { name: ru ? 'Обновить список' : 'Refresh list', exact: true }).click()
    await expect(area.getByRole('alert')).toHaveCount(0)
    await context.clearCookies()
    await area.getByRole('button', { name: ru ? 'Обновить список' : 'Refresh list', exact: true }).click()
    await expect(page.locator('#admin-secret')).toBeVisible()
    await expect(area).toHaveCount(0)
  })
}
