import { expect, test } from '@playwright/test'

for (const language of ['ru', 'en']) {
  test(`publish, preview, edit and delete without losing media (${language})`, async ({ page }, info) => {
    await page.addInitScript(language => { localStorage.setItem('stereoDamageLanguage', language); localStorage.setItem('stereoDamageTheme', language === 'ru' ? 'dark' : 'light') }, language)
    const ru = language === 'ru'
    const errors: string[] = []
    page.on('pageerror', error => errors.push(error.message))
    await page.goto('/admin')
    await page.locator('#admin-secret').fill('browser-test-secret')
    await page.getByRole('button', { name: ru ? 'Войти' : 'Sign in', exact: true }).click()
    const writing = page.locator('#admin-write')
    const title = `Publishing ${language} ${info.project.name}`
    await writing.getByLabel(ru ? 'Заголовок' : 'Title', { exact: true }).fill(title)
    await writing.getByRole('textbox', { name: ru ? 'Текст поста' : 'Post body' }).fill('A complete long-form story to publish.')
    const picker = page.waitForEvent('filechooser')
    await writing.getByRole('button', { name: ru ? 'Добавить медиа / файл' : 'Insert media / file' }).click()
    await (await picker).setFiles({ name: 'story.txt', mimeType: 'text/plain', buffer: Buffer.from('Story attachment') })
    await expect(writing.locator('figure')).toBeVisible()
    await writing.getByRole('button', { name: ru ? 'Предпросмотр' : 'Preview', exact: true }).click()
    await expect(writing.locator('.post-body')).toContainText('story.txt')
    await page.route('**/api/v1/admin/posts', route => route.request().method() === 'POST' ? route.fulfill({ status: 503, json: { error: { code: 'unavailable', message: 'Unavailable' } } }) : route.continue())
    await writing.getByRole('button', { name: ru ? 'Опубликовать' : 'Publish', exact: true }).click()
    await expect(writing.getByRole('alert')).toBeVisible()
    await expect(writing.locator('.post-body')).toContainText('A complete long-form story')
    await page.unroute('**/api/v1/admin/posts')
    const created = page.waitForResponse(response => response.url().endsWith('/admin/posts') && response.request().method() === 'POST')
    await writing.getByRole('button', { name: ru ? 'Опубликовать' : 'Publish', exact: true }).click()
    const post = await (await created).json()
    await expect(writing.getByRole('status')).toContainText(ru ? 'Пост сохранён.' : 'Post saved.')
    expect(await page.evaluate(() => localStorage.getItem('stereoDamageDraft:new'))).toBeNull()
    const before = await (await page.request.get(`/api/v1/admin/posts/${post.id}`)).json()
    const row = page.locator(`[data-post-id="${post.id}"]`)
    await row.getByRole('button', { name: ru ? 'Редактировать' : 'Edit', exact: true }).click()
    const editor = page.locator('#admin-edit-post')
    await editor.getByLabel(ru ? 'Заголовок' : 'Title', { exact: true }).fill(`${title} changed`)
    await expect(editor.locator('figure')).toHaveText('story.txt')
    await page.route(`**/api/v1/admin/posts/${post.id}`, route => route.request().method() === 'PUT' ? route.abort() : route.continue())
    await editor.getByRole('button', { name: ru ? 'Сохранить изменения' : 'Save changes', exact: true }).click()
    await expect(editor.getByRole('alert')).toBeVisible()
    await page.unroute(`**/api/v1/admin/posts/${post.id}`)
    await editor.getByRole('button', { name: ru ? 'Закрыть редактор' : 'Close editor', exact: true }).click()
    await row.getByRole('button', { name: ru ? 'Редактировать' : 'Edit', exact: true }).click()
    await expect(editor.getByLabel(ru ? 'Заголовок' : 'Title', { exact: true })).toHaveValue(`${title} changed`)
    await editor.getByRole('button', { name: ru ? 'Сохранить изменения' : 'Save changes', exact: true }).click()
    await expect(editor).toHaveCount(0)
    const after = await (await page.request.get(`/api/v1/admin/posts/${post.id}`)).json()
    expect(after.slug).toBe(before.slug)
    expect(after.blocks).toEqual(before.blocks)
    expect(after.preview_media).toEqual(before.preview_media)
    expect(after.title).toBe(`${title} changed`)
    const publicPost = await (await page.request.get(`/api/v1/posts/${post.slug}`)).json()
    expect(publicPost.title).toBe(after.title)
    page.once('dialog', dialog => dialog.dismiss())
    await row.getByRole('button', { name: ru ? 'Удалить пост' : 'Delete post', exact: true }).click()
    await expect(row).toBeVisible()
    page.once('dialog', dialog => dialog.accept())
    await row.getByRole('button', { name: ru ? 'Удалить пост' : 'Delete post', exact: true }).click()
    await expect(row).toHaveCount(0)
    expect((await page.request.get(`/api/v1/posts/${post.slug}`)).status()).toBe(404)
    expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
    expect(errors).toEqual([])
  })
}

test('legacy rich/media round trip, unsupported guard and cursor list', async ({ page }, info) => {
  await page.goto('/admin')
  await page.locator('#admin-secret').fill('browser-test-secret')
  await page.getByRole('button', { name: 'Войти', exact: true }).click()
  const session = await (await page.request.get('/api/v1/admin/session')).json()
  const media = { type: 'media', mediaKind: 'image', src: '/uploads/fixture.svg', caption: 'Legacy caption', alt: 'Legacy alt', name: 'Legacy image', spoiler: true }
  const cover = { mediaKind: 'image', src: '/uploads/fixture.svg', caption: '', alt: 'Cover', name: '' }
  const response = await page.request.post('/api/v1/admin/posts', { headers: { 'X-CSRF-Token': session.csrf_token }, data: { title: `Legacy ${info.project.name}`, blocks: [{ type: 'paragraph', text: 'Old plain paragraph' }, media], preview_media: cover } })
  expect(response.status()).toBe(201)
  const post = await response.json()
  const list = page.locator('#admin-posts')
  await list.getByRole('button', { name: 'Обновить список' }).click()
  const row = list.locator(`[data-post-id="${post.id}"]`)
  await page.route(`**/api/v1/admin/posts/${post.id}`, route => route.fulfill({ json: { ...post, blocks: [{ type: 'unrecognized-legacy-block', data: 'must survive' }] } }))
  await row.getByRole('button', { name: 'Редактировать', exact: true }).click()
  await expect(list.getByRole('alert')).toContainText('неподдерживаемые данные')
  await expect(page.locator('#admin-edit-post')).toHaveCount(0)
  await page.unroute(`**/api/v1/admin/posts/${post.id}`)
  await row.getByRole('button', { name: 'Редактировать', exact: true }).click()
  const editor = page.locator('#admin-edit-post')
  const text = editor.locator('.tiptap p').first()
  await text.click()
  await page.keyboard.press('Home')
  await page.keyboard.press('Shift+End')
  await editor.getByRole('button', { name: 'Жирный', exact: true }).click()
  await editor.getByRole('button', { name: 'Сохранить изменения', exact: true }).click()
  await expect(editor).toHaveCount(0)
  const saved = await (await page.request.get(`/api/v1/admin/posts/${post.id}`)).json()
  expect(saved.blocks[0].text).toBe('Old plain paragraph')
  expect(saved.blocks[0].content[0].marks).toEqual([{ type: 'bold' }])
  expect(saved.blocks[1]).toEqual(media)
  expect(saved.preview_media).toEqual(cover)
  await list.getByRole('button', { name: 'Загрузить ещё' }).click()
  await expect(list.locator('li')).toHaveCount(20)
  const ids = await list.locator('li').evaluateAll(nodes => nodes.map(node => node.getAttribute('data-post-id')))
  expect(new Set(ids).size).toBe(ids.length)
  await page.request.delete(`/api/v1/admin/posts/${post.id}`, { headers: { 'X-CSRF-Token': session.csrf_token } })
})
