import { expect, test } from '@playwright/test'

test('v1 settings survive hydration/reload, and the compact shell works on mobile', async ({ page }, testInfo) => {
  const errors: string[] = []
  page.on('pageerror', error => errors.push(error.message))
  page.on('console', message => { if (message.type() === 'warning' || message.type() === 'error') errors.push(message.text()) })
  await page.addInitScript(() => {
    if (!localStorage.getItem('stereoDamageLanguage')) {
      localStorage.setItem('stereoDamageLanguage', 'en')
      localStorage.setItem('stereoDamageTheme', 'dark')
      localStorage.setItem('stereoDamageFeedView', 'grid')
      localStorage.setItem('stereoDamageSmoothScroll', 'on')
      localStorage.setItem('stereoDamageReadingProgress', '{"1":{"progress":0.5}}')
    }
  })
  await page.goto('/')
  await expect(page.getByRole('heading', { name: 'Posts', exact: true })).toBeVisible()
  await expect(page.locator('html')).toHaveAttribute('data-theme', 'dark')
  await expect(page.locator('html')).toHaveAttribute('lang', 'en')
  expect(await page.locator('a[href*="/admin"]').count()).toBe(0)
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
  expect(await page.evaluate(() => getComputedStyle(document.documentElement).scrollBehavior)).not.toBe('smooth')
  const summary = page.locator('summary')
  await summary.focus()
  await summary.press('Enter')
  await page.getByRole('button', { name: 'Light', exact: true }).click()
  await expect(page.locator('html')).toHaveAttribute('data-theme', 'light')
  await page.getByRole('button', { name: 'Русский', exact: true }).click()
  await expect(page.getByRole('heading', { name: 'Посты', exact: true })).toBeVisible()
  await page.keyboard.press('Escape')
  await expect(summary).toBeFocused()
  await expect(page.locator('details')).not.toHaveAttribute('open', '')
  await page.reload()
  await expect(page.locator('html')).toHaveAttribute('data-theme', 'light')
  await expect(page.locator('html')).toHaveAttribute('lang', 'ru')
  expect(await page.evaluate(() => localStorage.getItem('stereoDamageFeedView'))).toBe('grid')
  expect(await page.evaluate(() => localStorage.getItem('stereoDamageReadingProgress'))).toBe('{"1":{"progress":0.5}}')
  await page.screenshot({ path: testInfo.outputPath('shell-light.png'), fullPage: true })
  await page.locator('summary').click()
  await page.getByRole('button', { name: 'Тёмная', exact: true }).click()
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
  await page.screenshot({ path: testInfo.outputPath('settings-dark.png'), fullPage: true })
  expect(errors).toEqual([])
})

test('theme is applied before app hydration and storage failures are harmless', async ({ page }) => {
  await page.emulateMedia({ colorScheme: 'dark', reducedMotion: 'reduce' })
  await page.addInitScript(() => {
    Object.defineProperty(window, 'localStorage', { get() { throw new DOMException('Blocked', 'SecurityError') } })
  })
  await page.route('**/_nuxt/*.js', route => route.abort())
  await page.goto('/', { waitUntil: 'domcontentloaded' })
  await expect(page.locator('html')).toHaveAttribute('data-theme', 'dark')
  await page.unroute('**/_nuxt/*.js')
  await page.reload()
  await page.locator('summary').click()
  await page.getByRole('button', { name: 'English', exact: true }).click()
  await expect(page.getByRole('heading', { name: 'Posts', exact: true })).toBeVisible()
  await page.getByRole('button', { name: 'Light', exact: true }).click()
  await expect(page.locator('html')).toHaveAttribute('data-theme', 'light')
})
