import { expect, test } from '@playwright/test'
test('long articles get stable anchors and an accessible responsive TOC; short ones do not', async ({ page }, testInfo) => {
  await page.goto('/posts/' + encodeURIComponent('привет-старый-веб'))
  const toc = page.getByRole('navigation', { name: 'Оглавление' })
  await expect(toc).toBeVisible()
  if (testInfo.project.name === 'mobile') await toc.locator('summary').click()
  const link = toc.getByRole('link', { name: 'Раздел 4', exact: true })
  const target = await link.getAttribute('href')
  await link.click()
  await expect(page).toHaveURL(/#section-/)
  await expect.poll(() => page.locator(target!).evaluate(node => Math.round(node.getBoundingClientRect().top))).toBeGreaterThanOrEqual(60)
  await expect.poll(() => page.locator(target!).evaluate(node => Math.round(node.getBoundingClientRect().top))).toBeLessThan(160)
  await expect(toc.locator(`a[href="${target}"]`)).toHaveAttribute('aria-current', 'location')
  if (testInfo.project.name === 'mobile') await expect(toc.locator('details')).not.toHaveAttribute('open', '')
  await page.reload()
  await expect(page.locator(target!)).toBeVisible()
  await page.goto('/posts/fixture-2')
  await expect(page.locator('.post-toc')).toHaveCount(0)
})
